config/routes.rb
Rails.application.routes.draw do

  resources :matieres
  get 'preinscription/index'
  get 'matieres/notes'

  resources :laclasses
  resources :students do
  	collection do
  		get 'search'
  	end
	end
  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.role_id == 1
        can :manage, :all
      else
        can :read, Laclasse
      end

      if user.role_id == 4
        can [:create, :read, :update], Student
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/laclasse.rb
class Laclasse < ApplicationRecord

	belongs_to :student
	
end

app/models/matiere.rb
class Matiere < ApplicationRecord

  belongs_to :student
  
end

app/models/role.rb
class Role < ApplicationRecord

	has_many :users
	
end

app/models/student.rb
class Student < ApplicationRecord

	include SearchCop

	belongs_to :laclasse
	belongs_to :matiere

	search_scope :search_student do
		attributes :first_name, :last_name

		options :first_name, :type => :fulltext
		options :last_name, :type => :fulltext
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
	before_create :set_default_role

	private
		def set_default_role
			self.role ||= Role.find_by_name('parent')
		end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/laclasses_controller.rb
class LaclassesController < ApplicationController
  before_action :set_laclass, only: [:show, :edit, :update, :destroy]

  # GET /laclasses
  # GET /laclasses.json
  def index
    @laclasses = Laclasse.all
    authorize! :read, @laclass
  end

  # GET /laclasses/1
  # GET /laclasses/1.json
  def show
    @students = Student.all.where(laclasse_id: @laclass.id, status: "Oui")
  end

  # GET /laclasses/new
  def new
    @laclass = Laclasse.new
  end

  # GET /laclasses/1/edit
  def edit
  end

  # POST /laclasses
  # POST /laclasses.json
  def create
    @laclass = Laclasse.new(laclass_params)

    #cancan vérifier la permission du user
    authorize! :create, @laclass

    respond_to do |format|
      if @laclass.save
        format.html { redirect_to @laclass, notice: 'Laclasse was successfully created.' }
        format.json { render :show, status: :created, location: @laclass }
      else
        format.html { render :new }
        format.json { render json: @laclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laclasses/1
  # PATCH/PUT /laclasses/1.json
  def update
    respond_to do |format|
      if @laclass.update(laclass_params)
        format.html { redirect_to @laclass, notice: 'Laclasse was successfully updated.' }
        format.json { render :show, status: :ok, location: @laclass }
      else
        format.html { render :edit }
        format.json { render json: @laclass.errors, status: :unprocessable_entity }
      end
    end
    authorize! :update, @laclass
  end

  # DELETE /laclasses/1
  # DELETE /laclasses/1.json
  def destroy
    authorize! :destroy, @laclass
    @laclass.destroy
    respond_to do |format|
      format.html { redirect_to laclasses_url, notice: 'Laclasse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laclass
      @laclass = Laclasse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laclass_params
      params.require(:laclasse).permit(:name)
    end
end

app/controllers/matieres_controller.rb
class MatieresController < ApplicationController
  before_action :set_matiere, only: [:show, :edit, :update, :destroy]

  # GET /matieres
  # GET /matieres.json
  def index
    @matieres = Matiere.all
  end

  def notes
    # @matieres = Matiere.all
  end

  # GET /matieres/1
  # GET /matieres/1.json
  def show
  end

  # GET /matieres/new
  def new
    @matiere = Matiere.new
  end

  # GET /matieres/1/edit
  def edit
  end

  # POST /matieres
  # POST /matieres.json
  def create
    @matiere = Matiere.new(matiere_params)

    respond_to do |format|
      if @matiere.save
        format.html { redirect_to @matiere, notice: 'Matiere was successfully created.' }
        format.json { render :show, status: :created, location: @matiere }
      else
        format.html { render :new }
        format.json { render json: @matiere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matieres/1
  # PATCH/PUT /matieres/1.json
  def update
    respond_to do |format|
      if @matiere.update(matiere_params)
        format.html { redirect_to @matiere, notice: 'Matiere was successfully updated.' }
        format.json { render :show, status: :ok, location: @matiere }
      else
        format.html { render :edit }
        format.json { render json: @matiere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matieres/1
  # DELETE /matieres/1.json
  def destroy
    @matiere.destroy
    respond_to do |format|
      format.html { redirect_to matieres_url, notice: 'Matiere was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matiere
      @matiere = Matiere.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matiere_params
      params.require(:matiere).permit(:maths, :pc, :svt, :anglais, :student_id)
    end
end

app/controllers/preinscription_controller.rb
class PreinscriptionController < ApplicationController

  def index
  	@students = Student.all.where(status: nil )
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:edit, :update, :show, :destroy]

  def index
  	@students = Student.all
  end

  def show
  end

  def search
    @students = Student.search_student(params[:q])
  end

  def new
  	@student = Student.new
  end

  def create
  	@student = Student.new(student_params)
  	if @student.save
  		redirect_to students_path, notice: 'Votre inscription a été bien prise en compte'
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    authorize! :update, @student
    if @student.update(student_params)
      redirect_to laclasses_path, notice: 'inscription validée'
    else
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, @student
    @student.destroy
    redirect_to laclasses_path, notice: 'Eleve supprimé'
  end

  private
  	def student_params
  		params.require(:student).permit(:first_name, :last_name, :birth_day, :status, :laclasse_id)
  	end

    def set_student
      @student = Student.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/laclasses_helper.rb
module LaclassesHelper
end

app/helpers/matieres_helper.rb
module MatieresHelper
end

app/helpers/preinscription_helper.rb
module PreinscriptionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/laclasses/_form.html.erb
<%= simple_form_for(@laclass) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/laclasses/edit.html.erb
<h1>Editing Laclass</h1>

<%= render 'form', laclass: @laclass %>

<%= link_to 'Show', @laclass %> |
<%= link_to 'Back', laclasses_path %>

app/views/laclasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Laclasses</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @laclasses.each do |laclass| %>
      <tr>
        <td><%= laclass.name %></td>
        <td><%= link_to 'Show', laclass %></td>
        <td><%= link_to 'Edit', edit_laclass_path(laclass) %></td>
        <td><%= link_to 'Destroy', laclass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laclass', new_laclass_path %>

app/views/laclasses/new.html.erb
<h1>New Laclass</h1>

<%= render 'form', laclass: @laclass %>

<%= link_to 'Back', laclasses_path %>

app/views/laclasses/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Date de Naissance</th>
      <th>Classe</th>
      <th>Status</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |s| %>
      <tr>
        <td><%= s.first_name %></td>
        <td><%= s.last_name %></td>
        <td><%= s.birth_day %></td>
        <td><%= s.laclasse.name %></td>
        <td><%= s.status %></td>
        <td><%= link_to 'Détails', s %></td>
        <td><%= link_to 'Modifier', edit_student_path(s) %></td>
        <td><%= link_to 'Supprimer', s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_laclass_path(@laclass) %> |
<%= link_to 'Back', laclasses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "School" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">School</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user.email, edit_user_registration_path  %></li>
              <li><%= link_to "Deconnexion", destroy_user_session_path, method: :delete  %></li>
            <% else %>
              <li><%= link_to "Inscription", new_user_registration_path %></li>
              <li><%= link_to "Connection", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= form_tag search_students_path, method: :get do %>
            <div class="row">
              <div class="col-md-8">
                <%= text_field_tag :q, nil, class: 'form-control', placeholder: 'Rechercher un éléve' %>
              </div>
              <div class="col-md-4">
                <%= submit_tag "Rechercher", class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <% if user_signed_in? && current_user.role_id == 1 %>
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li><%= link_to "Gestion des Class", laclasses_path  %></li>
                <li><%= link_to "Gestion des notes", matieres_path  %></li>
                <li><%= link_to "Gestion des préinscriptions", preinscription_index_path  %></li>
              </ul>
            </div><!--/.well -->
          <% end %>
          <% if user_signed_in? && current_user.role_id == 4 %>
            <div class="well sidebar-nav">
              <h3>Bare de suivi</h3>
              <ul class="nav nav-list">
                <li><%= link_to "Inscrire un élève", new_student_path  %></li>
                <li><%= link_to "Mes élèves", students_path  %></li>
                <li><%= link_to "Voir les notes", matieres_path  %></li>
              </ul>
            </div><!--/.well -->
          <% end %>
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/matieres/_form.html.erb
<%= simple_form_for(@matiere) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :maths %>
    <%= f.input :pc %>
    <%= f.input :svt %>
    <%= f.input :anglais %>
    <%= f.association :student, :collection => Student.all, :method_value => :id, :label_method => :first_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/matieres/edit.html.erb
<h1>Modifier les notes de <%= @matiere.student.first_name + " " + @matiere.student.last_name %></h1>
<%= render 'form', matiere: @matiere %>

<%= link_to 'Show', @matiere %> |
<%= link_to 'Back', matieres_path %>

app/views/matieres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matieres</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Prénom & Nom</th>
      <th>Maths</th>
      <th>Pc</th>
      <th>Svt</th>
      <th>Anglais</th>
      <% if current_user.role_id == 1 %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @matieres.each do |matiere| %>
      <tr>
        <td><%= matiere.student.first_name + " " + matiere.student.last_name %></td>
        <td><%= matiere.maths %></td>
        <td><%= matiere.pc %></td>
        <td><%= matiere.svt %></td>
        <td><%= matiere.anglais %></td>
        <% if current_user.role_id == 1 %>
          <td><%= link_to 'Show', matiere %></td>
          <td><%= link_to 'Edit', edit_matiere_path(matiere) %></td>
          <td><%= link_to 'Destroy', matiere, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role_id == 1 %>
  <%= link_to 'Ajouter une note', new_matiere_path, class: 'btn btn-warning' %>
<% end %>

app/views/matieres/new.html.erb
<h1>New Matiere</h1>

<%= render 'form', matiere: @matiere %>

<%= link_to 'Back', matieres_path %>

app/views/matieres/notes.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Prénom & Nom</th>
      <th>Maths</th>
      <th>Pc</th>
      <th>Svt</th>
      <th>Anglais</th>
    </tr>
  </thead>

  <tbody>
    <% @matieres.each do |matiere| %>
      <tr>
        <td><%= matiere.student.first_name + " " + matiere.student.last_name %></td>
        <td><%= matiere.maths %></td>
        <td><%= matiere.pc %></td>
        <td><%= matiere.svt %></td>
        <td><%= matiere.anglais %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/matieres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Maths:</strong>
  <%= @matiere.maths %>
</p>

<p>
  <strong>Pc:</strong>
  <%= @matiere.pc %>
</p>

<p>
  <strong>Svt:</strong>
  <%= @matiere.svt %>
</p>

<p>
  <strong>Anglais:</strong>
  <%= @matiere.anglais %>
</p>

<p>
  <strong>Student:</strong>
  <%= @matiere.student.first_name + " " + @matiere.student.last_name %>
</p>

<%= link_to 'Edit', edit_matiere_path(@matiere) %> |
<%= link_to 'Back', matieres_path %>

app/views/preinscription/index.html.erb
<h1>Les élèves non inscris</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Date de Naissance</th>
      <th>Classe</th>
      <th>Status</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |s| %>
      <tr>
        <td><%= s.first_name %></td>
        <td><%= s.last_name %></td>
        <td><%= s.birth_day %></td>
        <td><%= s.laclasse.name %></td>
        <td><%= s.status %></td>
        <td><%= link_to 'Edit', edit_student_path(s) %></td>
        <td><%= link_to 'Edit', edit_student_path(s) %></td>
        <td><%= link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/_form.html.erb
<%= simple_form_for @student, html: { class: 'form-horizontal' } do |f| %>

	<%= f.input :first_name, label: 'Prénom', input_html: { class: 'form-control'} %>
	<%= f.input :last_name, label: 'Nom', input_html: { class: 'form-control'} %>
	<%= f.input :birth_day, as: :date, label: 'Date de naissance', input_html: { class: 'form-control'} %>
	<%= f.association :laclasse, :collection => Laclasse.all, :value_method => :id, input_html: { class: 'form-control'} %>
	<% if current_user.role_id == 1 %>
		<%= f.input :status, priority: ["Non"], collection: ["Non", "Oui"] %>
	<% end %>
	<%= f.button :submit, "Valider", class: 'btn btn-primary' %>
	
<% end %>

app/views/students/edit.html.erb
<h2>Modifications</h2>
<%= render 'form' %>

app/views/students/index.html.erb
<h2>Liste des élèves</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Date de Naissance</th>
      <th>Classe</th>
      <th>Status</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |s| %>
      <tr>
        <td><%= s.first_name %></td>
        <td><%= s.last_name %></td>
        <td><%= s.birth_day %></td>
        <td><%= s.laclasse.name %></td>
        <td><%= s.status %></td>
        <td><%= link_to 'Show', s %></td>
        <td><%= link_to 'Edit', edit_student_path(s) %></td>
        <td><%= link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laclass', new_student_path %>

app/views/students/new.html.erb
<h2>Inscription</h2>
<%= render 'form' %>

app/views/students/search.html.erb
<h2>Resultat</h2>
<ul>
	<% @students.each do |f| %>
		<li>
			<%= f.first_name %>
			<%= f.last_name %>
		</li>
	<% end %>
</ul>

app/views/students/show.html.erb
<h2><%= @student.first_name.capitalize + " " + @student.last_name.upcase %></h2>
<p>Eleve de classe <%= @student.laclasse_id %></p>
<p>Né le <%= @student.birth_day %></p>
<%= link_to "Ajouter une note", new_matiere_path, class: 'btn btn-primary'  %>